package exercise8

object TestMovieDB {
    /**
     * Test data: actor pairs with the most costarred movies
     */
    internal val ACTOR_PAIRS_WITH_MOST_COSTARRED_MOVIES = listOf(
        MovieActor(name="Daniel Radcliffe") to MovieActor(name="Emma Watson"),
        MovieActor(name="Daniel Radcliffe") to MovieActor(name="Rupert Grint"),
        MovieActor(name="Emma Watson") to MovieActor(name="Rupert Grint"),
    )

    /**
     * Test data: Director with the most directed movies.
     */
    internal val DIRECTOR_WITH_MOST_MOVIES_DIRECTED = "Steven Spielberg"

    /**
     * Test data: actors with their movies.
     */
    internal val ACTORS_TO_EXPECTED_MOVIES: Map<MovieActor, List<String>> = mapOf(
        MovieActor("Johnny Depp") to listOf(
            "Pirates of the Caribbean: On Stranger Tides",
            "Pirates of the Caribbean: At World's End",
            "The Lone Ranger",
            "Pirates of the Caribbean: Dead Man's Chest",
            "Charlie and the Chocolate Factory",
            "Pirates of the Caribbean: The Curse of the Black Pearl",
            "Rango",
            "The Tourist",
            "Transcendence",
            "Public Enemies",
            "The Astronaut's Wife",
        ),
        MovieActor("Robert Downey Jr.") to listOf(
            "Avengers: Age of Ultron",
            "Captain America: Civil War",
            "The Avengers",
            "Iron Man 3",
            "Iron Man 2",
            "Iron Man",
            "Sherlock Holmes: A Game of Shadows",
            "Tropic Thunder",
            "Sherlock Holmes",

            ),
        MovieActor("Ben Affleck") to listOf("Batman v Superman: Dawn of Justice"),
        MovieActor("Gwyneth Paltrow") to listOf(
            "Iron Man 3",
            "Iron Man 2",
            "Iron Man",
            "Sky Captain and the World of Tomorrow",

            ),
        MovieActor("Brad Pitt") to listOf(
            "Troy",
            "The Curious Case of Benjamin Button",
            "Megamind",
            "Ocean's Twelve",
            "Mr. & Mrs. Smith",
            "Spy Game",
            "The Devil's Own",
            "Ocean's Eleven",
            "Ocean's Thirteen",
            "Inglourious Basterds",
            "Seven Years in Tibet",
        ),
        MovieActor("Tommy Lee Jones") to listOf(
            "Men in Black 3",
            "Men in Black II",
            "Captain America: The First Avenger",
            "Jason Bourne",
            "Batman Forever",
            "Men in Black",
            "Volcano",
            "Double Jeopardy",
        ),
    )

    /**
     * Test data: movies by the year of their release.
     */
    internal val MOVIES_PER_YEAR = mapOf(
        1991 to listOf(
            "Terminator 2: Judgment Day",
            "Hook",
        ),
        1999 to listOf(
            "Payback",
            "Message in a Bottle",
            "Edtv",
            "The Out-of-Towners",
            "Star Wars: Episode I - The Phantom Menace",
            "The Haunting",
            "Inspector Gadget",
            "Runaway Bride",
            "The Astronaut's Wife",
            "The 13th Warrior",
            "Chill Factor",
            "Double Jeopardy",
            "Three Kings",
            "The Insider",
            "Toy Story 2",
            "The Bone Collector",
            "The World Is Not Enough",
            "End of Days",
            "Bicentennial Man",
            "Man on the Moon",
        ),
        2002 to listOf(
            "Red Dragon",
            "The Lord of the Rings: The Two Towers",
            "The Adventures of Pluto Nash",
            "I Spy",
            "Harry Potter and the Chamber of Secrets",
            "Bad Company",
            "Hart's War",
            "K-19: The Widowmaker",
            "Windtalkers",
            "Collateral Damage",
            "We Were Soldiers",
            "The Time Machine",
            "Signs",
            "Scooby-Doo",
            "Spirit: Stallion of the Cimarron",
            "Gangs of New York",
            "Die Another Day",
            "Ballistic: Ecks vs. Sever",
            "Spider-Man",
            "Men in Black II",
        ),
        2003 to listOf(
            "Tears of the Sun",
            "X2",
            "The Matrix Reloaded",
            "Bruce Almighty",
            "Finding Nemo",
            "Hollywood Homicide",
            "Hulk",
            "Charlie's Angels: Full Throttle",
            "Terminator 3: Rise of the Machines",
            "Pirates of the Caribbean: The Curse of the Black Pearl",
            "The League of Extraordinary Gentlemen",
            "Bad Boys II",
            "Lara Croft Tomb Raider: The Cradle of Life",
            "Seabiscuit",
            "S.W.A.T.",
            "The Rundown",
            "The Matrix Revolutions",
            "Master and Commander: The Far Side of the World",
            "Looney Tunes: Back in Action",
            "The Haunted Mansion",
            "Timeline",
            "The Lord of the Rings: The Return of the King",
            "The Last Samurai",
            "Something's Gotta Give",
            "Cold Mountain",
        ),
        2016 to listOf(
            "Kung Fu Panda 3",
            "The Finest Hours",
            "Gods of Egypt",
            "Allegiant",
            "Batman v Superman: Dawn of Justice",
            "The Huntsman: Winter's War",
            "The Jungle Book",
            "Captain America: Civil War",
            "The Angry Birds Movie",
            "X-Men: Apocalypse",
            "Warcraft",
            "The BFG",
            "Teenage Mutant Ninja Turtles: Out of the Shadows",
            "Now You See Me 2",
            "The Secret Life of Pets",
            "Independence Day: Resurgence",
            "Star Trek Beyond",
            "Ghostbusters",
            "Jason Bourne",
            "Suicide Squad",
            "Ben-Hur",
        )
    )

    /**
     * Test data: The top 10 best grossing movies.
     */
    internal val TOP_10_BEST_GROSSING_MOVIES = listOf(
        "Avatar",
        "Titanic",
        "Furious 7",
        "The Avengers",
        "Avengers: Age of Ultron",
        "Frozen",
        "Minions",
        "The Lord of the Rings: The Return of the King",
        "Iron Man 3",
        "Transformers: Dark of the Moon",
    )

    /**
     * Test data: The top 10 best rated movies.
     */
    internal val TOP_10_BEST_RATED_MOVIES = listOf(
        "Minions",
        "Interstellar",
        "Guardians of the Galaxy",
        "Mad Max: Fury Road",
        "Pirates of the Caribbean: The Curse of the Black Pearl",
        "Dawn of the Planet of the Apes",
        "The Hunger Games: Mockingjay - Part 1",
        "Big Hero 6",
        "Terminator Genisys",
        "Captain America: Civil War"
    )

    /**
     * Test data: Actors with their best rated movies.
     */
    internal val ACTOR_TO_BEST_RATED_MOVIES = mapOf(
        MovieActor("Johnny Depp") to "Pirates of the Caribbean: The Curse of the Black Pearl",
        MovieActor("Robert Downey Jr.") to "Captain America: Civil War",
        MovieActor("Ben Affleck") to "Batman v Superman: Dawn of Justice",
        MovieActor("Gwyneth Paltrow") to "Iron Man",
        MovieActor("Brad Pitt") to "Ocean's Twelve",
        MovieActor("Tommy Lee Jones") to "Men in Black"
    )

    /**
     * Test data: Movies by genre.
     */
    internal val MOVIES_BY_GENRE = mapOf(
        "Action" to listOf(
            "Die Hard 2",
            "Terminator 2: Judgment Day",
            "Batman Returns",
            "Cliffhanger",
            "Braveheart",
            "Batman Forever",
            "Cutthroat Island",
            "Mission: Impossible",
            "The Rock",
            "Eraser",
            "Independence Day",
            "Ransom",
            "The Saint",
            "Volcano",
            "The Fifth Element",
            "The Lost World: Jurassic Park",
            "Con Air",
            "Speed 2: Cruise Control",
            "Batman & Robin",
            "Face/Off",
            "Men in Black",
            "Conspiracy Theory",
            "Starship Troopers",
            "Alien: Resurrection",
            "Tomorrow Never Dies",
            "Deep Impact",
            "Six Days Seven Nights",
            "Lethal Weapon 4",
            "The Mask of Zorro",
            "The Siege",
            "Enemy of the State",
            "Star Trek: Insurrection",
            "Mighty Joe Young",
            "Payback",
            "Star Wars: Episode I - The Phantom Menace",
            "Inspector Gadget",
            "The 13th Warrior",
            "Chill Factor",
            "Three Kings",
            "The World Is Not Enough",
            "End of Days",
            "Gladiator",
            "Mission: Impossible II",
            "Gone in Sixty Seconds",
            "Titan A.E.",
            "The Patriot",
            "X-Men",
            "Hollow Man",
            "Charlie's Angels",
            "Red Planet",
            "Vertical Limit",
            "Monkeybone",
            "The Mummy Returns",
            "Swordfish",
            "Lara Croft: Tomb Raider",
            "Final Fantasy: The Spirits Within",
            "Planet of the Apes",
            "The Last Castle",
            "Spy Game",
            "The Lord of the Rings: The Fellowship of the Ring",
            "Black Hawk Down",
            "Collateral Damage",
            "We Were Soldiers",
            "The Time Machine",
            "Spider-Man",
            "Bad Company",
            "Windtalkers",
            "Men in Black II",
            "The Adventures of Pluto Nash",
            "Ballistic: Ecks vs. Sever",
            "I Spy",
            "Die Another Day",
            "The Lord of the Rings: The Two Towers",
            "Tears of the Sun",
            "X2",
            "The Matrix Reloaded",
            "Hollywood Homicide",
            "Hulk",
            "Charlie's Angels: Full Throttle",
            "Terminator 3: Rise of the Machines",
            "Pirates of the Caribbean: The Curse of the Black Pearl",
            "The League of Extraordinary Gentlemen",
            "Bad Boys II",
            "Lara Croft Tomb Raider: The Cradle of Life",
            "S.W.A.T.",
            "The Rundown",
            "The Matrix Revolutions",
            "Timeline",
            "The Lord of the Rings: The Return of the King",
            "The Last Samurai",
            "Man on Fire",
            "The Stepford Wives",
            "The Chronicles of Riddick",
            "Spider-Man 2",
            "I, Robot",
            "Catwoman",
            "The Bourne Supremacy",
            "AVP: Alien vs. Predator",
            "Sky Captain and the World of Tomorrow",
            "The Incredibles",
            "National Treasure",
            "Kingdom of Heaven",
            "A Sound of Thunder",
            "Mr. & Mrs. Smith",
            "Batman Begins",
            "The Island",
            "Stealth",
            "The Great Raid",
            "The Brothers Grimm",
            "The Legend of Zorro",
            "King Kong",
            "Munich",
            "Mission: Impossible III",
            "Poseidon",
            "X-Men: The Last Stand",
            "The Fast and the Furious: Tokyo Drift",
            "Pirates of the Caribbean: Dead Man's Chest",
            "Superman Returns",
            "Children of Men",
            "Casino Royale",
            "Blood Diamond",
            "Eragon",
            "디워",
            "Ghost Rider",
            "Pirates of the Caribbean: At World's End",
            "4: Rise of the Silver Surfer",
            "Live Free or Die Hard",
            "Transformers",
            "The Bourne Ultimatum",
            "The Kingdom",
            "Beowulf",
            "I Am Legend",
            "Iron Man",
            "Speed Racer",
            "Indiana Jones and the Kingdom of the Crystal Skull",
            "You Don't Mess with the Zohan",
            "Get Smart",
            "Wanted",
            "Hancock",
            "The Mummy: Tomb of the Dragon Emperor",
            "The Dark Knight",
            "Tropic Thunder",
            "Babylon A.D.",
            "Eagle Eye",
            "Body of Lies",
            "Quantum of Solace",
            "Dragonball Evolution",
            "X-Men Origins: Wolverine",
            "Star Trek",
            "Night at the Museum: Battle of the Smithsonian",
            "Transformers: Revenge of the Fallen",
            "G-Force",
            "G.I. Joe: The Rise of Cobra",
            "Inglourious Basterds",
            "Surrogates",
            "2012",
            "Avatar",
            "Sherlock Holmes",
            "The Book of Eli",
            "Green Zone",
            "Clash of the Titans",
            "Iron Man 2",
            "Prince of Persia: The Sands of Time",
            "Killers",
            "Knight and Day",
            "The Last Airbender",
            "The Sorcerer's Apprentice",
            "Inception",
            "Salt",
            "The Expendables",
            "Megamind",
            "Unstoppable",
            "The Nutcracker: The Untold Story",
            "The Tourist",
            "TRON: Legacy",
            "The Green Hornet",
            "Battle: Los Angeles",
            "Sucker Punch",
            "Thor",
            "Pirates of the Caribbean: On Stranger Tides",
            "X-Men: First Class",
            "Green Lantern",
            "Transformers: Dark of the Moon",
            "Captain America: The First Avenger",
            "Rise of the Planet of the Apes",
            "The Three Musketeers",
            "Real Steel",
            "Tower Heist",
            "Immortals",
            "Sherlock Holmes: A Game of Shadows",
            "Mission: Impossible - Ghost Protocol",
            "Journey 2: The Mysterious Island",
            "Underworld: Awakening",
            "Safe House",
            "The Avengers",
            "Men in Black 3",
            "Brave",
            "The Amazing Spider-Man",
            "The Dark Knight Rises",
            "The Bourne Legacy",
            "The Expendables 2",
            "Skyfall",
            "Life of Pi",
            "The Hobbit: An Unexpected Journey",
            "Jack the Giant Slayer",
            "Olympus Has Fallen",
            "G.I. Joe: Retaliation",
            "Oblivion",
            "Iron Man 3",
            "Star Trek Into Darkness",
            "After Earth",
            "Man of Steel",
            "White House Down",
            "The Lone Ranger",
            "Pacific Rim",
            "R.I.P.D.",
            "RED 2",
            "Elysium",
            "Ender's Game",
            "Thor: The Dark World",
            "The Hunger Games: Catching Fire",
            "47 Ronin",
            "The Legend of Hercules",
            "The Monuments Men",
            "Pompeii",
            "300: Rise of an Empire",
            "Divergent",
            "The Amazing Spider-Man 2",
            "X-Men: Days of Future Past",
            "Edge of Tomorrow",
            "Maleficent",
            "How to Train Your Dragon 2",
            "Transformers: Age of Extinction",
            "Dawn of the Planet of the Apes",
            "Hercules",
            "Guardians of the Galaxy",
            "The Expendables 3",
            "Teenage Mutant Ninja Turtles",
            "Dracula Untold",
            "Big Hero 6",
            "Exodus: Gods and Kings",
            "The Hobbit: The Battle of the Five Armies",
            "Jupiter Ascending",
            "Furious 7",
            "Avengers: Age of Ultron",
            "Mad Max: Fury Road",
            "San Andreas",
            "Terminator Genisys",
            "Ant-Man",
            "Pixels",
            "Mission: Impossible - Rogue Nation",
            "The Man from U.N.C.L.E.",
            "Spectre",
            "The Hunger Games: Mockingjay - Part 2",
            "In the Heart of the Sea",
            "Point Break",
            "Kung Fu Panda 3",
            "The Finest Hours",
            "Batman v Superman: Dawn of Justice",
            "The Huntsman: Winter's War",
            "Captain America: Civil War",
            "Warcraft",
            "Teenage Mutant Ninja Turtles: Out of the Shadows",
            "Now You See Me 2",
            "Independence Day: Resurgence",
            "Star Trek Beyond",
            "Ghostbusters",
            "Jason Bourne",
            "Suicide Squad",
        ),
        "Comedy" to listOf(
            "Hook",
            "Mars Attacks!",
            "Men in Black",
            "Flubber",
            "Six Days Seven Nights",
            "Doctor Dolittle",
            "Lethal Weapon 4",
            "A Bug's Life",
            "Babe: Pig in the City",
            "Edtv",
            "The Out-of-Towners",
            "Inspector Gadget",
            "Runaway Bride",
            "Chill Factor",
            "Three Kings",
            "Toy Story 2",
            "Bicentennial Man",
            "Man on the Moon",
            "The Flintstones in Viva Rock Vegas",
            "Nutty Professor II: The Klumps",
            "102 Dalmatians",
            "Charlie's Angels",
            "How the Grinch Stole Christmas",
            "The Emperor's New Groove",
            "What Women Want",
            "Monkeybone",
            "Town & Country",
            "Monsters, Inc.",
            "Spirit: Stallion of the Cimarron",
            "Bad Company",
            "Scooby-Doo",
            "Men in Black II",
            "The Adventures of Pluto Nash",
            "I Spy",
            "Bruce Almighty",
            "Hollywood Homicide",
            "Charlie's Angels: Full Throttle",
            "Bad Boys II",
            "The Rundown",
            "Looney Tunes: Back in Action",
            "The Haunted Mansion",
            "Something's Gotta Give",
            "50 First Dates",
            "Shrek 2",
            "The Stepford Wives",
            "Spanglish",
            "Son of the Mask",
            "Robots",
            "Mr. & Mrs. Smith",
            "Charlie and the Chocolate Factory",
            "The Brothers Grimm",
            "Chicken Little",
            "Fun with Dick and Jane",
            "Over the Hedge",
            "Cars",
            "Click",
            "Monster House",
            "Flushed Away",
            "Happy Feet",
            "The Holiday",
            "Shrek the Third",
            "Surf's Up",
            "Ratatouille",
            "The Simpsons Movie",
            "Bee Movie",
            "Enchanted",
            "Astérix aux Jeux Olympiques",
            "Fool's Gold",
            "Kung Fu Panda",
            "You Don't Mess with the Zohan",
            "Get Smart",
            "Tropic Thunder",
            "Bolt",
            "Four Christmases",
            "Yes Man",
            "Bedtime Stories",
            "Up",
            "Night at the Museum: Battle of the Smithsonian",
            "Land of the Lost",
            "Ice Age: Dawn of the Dinosaurs",
            "G-Force",
            "Funny People",
            "Cloudy with a Chance of Meatballs",
            "Couples Retreat",
            "It's Complicated",
            "Shrek Forever After",
            "Killers",
            "Knight and Day",
            "Toy Story 3",
            "Grown Ups",
            "The Sorcerer's Apprentice",
            "Cats & Dogs 2 : The Revenge of Kitty Galore",
            "Dinner for Schmucks",
            "Megamind",
            "Yogi Bear",
            "How Do You Know",
            "Gulliver's Travels",
            "The Green Hornet",
            "The Dilemma",
            "Just Go with It",
            "Rango",
            "The Hangover Part II",
            "Cars 2",
            "Zookeeper",
            "Tower Heist",
            "Jack and Jill",
            "Happy Feet Two",
            "Alvin and the Chipmunks: Chipwrecked",
            "Mirror Mirror",
            "Men in Black 3",
            "Rock of Ages",
            "Brave",
            "Hotel Transylvania",
            "The Croods",
            "Despicable Me 2",
            "Grown Ups 2",
            "R.I.P.D.",
            "RED 2",
            "Cloudy with a Chance of Meatballs 2",
            "The Secret Life of Walter Mitty",
            "The Wolf of Wall Street",
            "Rio 2",
            "How to Train Your Dragon 2",
            "Teenage Mutant Ninja Turtles",
            "Big Hero 6",
            "Penguins of Madagascar",
            "Night at the Museum: Secret of the Tomb",
            "The SpongeBob Movie: Sponge Out of Water",
            "Inside Out",
            "Minions",
            "Pixels",
            "The Man from U.N.C.L.E.",
            "Hotel Transylvania 2",
            "Kung Fu Panda 3",
            "Teenage Mutant Ninja Turtles: Out of the Shadows",
            "Now You See Me 2",
            "Ghostbusters",
        )
    )
}