# This is a basic workflow to help you get started with Actions

name: Test Kotlin Programming Language Course Submissions 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: ./gradlew test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Submission Test Results            # Name of the check run which will be created
          path: '**/build/test-results/test/TEST-*.xml'   # Path to test results
          reporter: java-junit
